#!/usr/bin/env python3
"""gen-atlas.py - generate (or verify) the atlas's `built` flags from the actual bundles.

The Product Artifact Atlas (atlas/atlas.html) shows, per catalog type, whether the library has
BUILT a bundle for it (the "Built" filter). That state lived in two hand-maintained copies - the
`built` boolean in atlas/catalog-data.json AND an identical inline copy embedded in atlas.html's
`<script id="catalog-data" type="application/json">` island - generated by nothing and checked by
nothing. It drifted: for weeks the atlas advertised four built bundles while twelve existed, on the
one surface that is public. Same failure class as the counts that PR #30 corrected, and as the
manifest that ADR 0018 solved for machine consumption: a derived fact kept honest only by memory.

This closes it the same way ADR 0018 closed the manifest. The `built` flag becomes a GENERATED fact,
derived from which catalog types have a bundle under templates/ (matched by each bundle meta's
catalog_ref, the 1-indexed position of its type in catalog-data.json). catalog-data.json is the
single source of truth for the type data; atlas.html's JSON island is regenerated to hold exactly
catalog-data.json's content, so the two can no longer disagree. `--check` regenerates in memory and
fails on drift, the same discipline gen-manifest, the link gate, and the dashes gate already use.

Only the `built` field is derived here. Every other field in catalog-data.json (categories, stages,
the per-type catalog data) is hand-maintained and preserved untouched.

Usage:
    python tools/gen-atlas.py            # rewrite catalog-data.json + atlas.html built flags in place
    python tools/gen-atlas.py --check    # exit 1 if either file has drifted from the bundles on disk

Exit 0 if written / in sync; 1 if --check finds drift (or the inputs are malformed).
"""

import json
import os
import re
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(SCRIPT_DIR, ".."))
TEMPLATES_DIR = os.path.join(ROOT, "templates")
CATALOG_JSON = os.path.join(ROOT, "atlas", "catalog-data.json")
ATLAS_HTML = os.path.join(ROOT, "atlas", "atlas.html")

# The JSON island in atlas.html: a self-contained data block the offline page reads. Its content is
# kept byte-identical to catalog-data.json so there is exactly one source of truth for the type data.
ISLAND_RE = re.compile(
    r'(<script id="catalog-data" type="application/json">)(.*?)(</script>)', re.S
)
# The digits after the key; tolerates a trailing inline comment (some metas write
# `catalog_ref: 29   # entry number in the master catalog`).
CATALOG_REF_RE = re.compile(r"^catalog_ref:\s*(\d+)", re.MULTILINE)

GREEN = "\033[32m"
RED = "\033[31m"
OFF = "\033[0m"


def read(path):
    with open(path, encoding="utf-8") as f:
        return f.read()


def built_catalog_refs():
    """The set of catalog numbers that have a built bundle, from each bundle meta's catalog_ref."""
    refs = set()
    missing = []
    for name in sorted(os.listdir(TEMPLATES_DIR)):
        d = os.path.join(TEMPLATES_DIR, name)
        meta = os.path.join(d, name + "_meta.yaml")
        if not os.path.isfile(meta):
            continue  # not a bundle dir (e.g. methodology.md, _working/)
        m = CATALOG_REF_RE.search(read(meta))
        if m:
            refs.add(int(m.group(1)))
        else:
            missing.append(name)
    return refs, missing


def rebuild_catalog_json_text(current_text, refs):
    """Return catalog-data.json's text with `built` set to (type is in refs), everything else kept.

    A type's catalog number is its 1-indexed position in the types array (the ordering the catalog's
    own numbering uses; verified: catalog_ref N maps to types[N-1]).
    """
    data = json.loads(current_text)
    types = data["types"]
    for i, t in enumerate(types):
        t["built"] = (i + 1) in refs
    # Exactly the serialization the committed file already uses (indent 2, unicode, no trailing NL).
    return json.dumps(data, indent=2, ensure_ascii=False)


def rebuild_atlas_html(current_html, catalog_json_text):
    """Return atlas.html with its JSON island replaced by catalog_json_text."""
    if not ISLAND_RE.search(current_html):
        raise SystemExit(RED + "FAIL" + OFF + "  atlas.html has no <script id=\"catalog-data\"> island")
    return ISLAND_RE.sub(
        lambda m: m.group(1) + catalog_json_text + m.group(3), current_html, count=1
    )


def main():
    check = "--check" in sys.argv[1:]

    if not os.path.isfile(CATALOG_JSON) or not os.path.isfile(ATLAS_HTML):
        print(RED + "FAIL" + OFF + "  atlas/catalog-data.json or atlas/atlas.html is missing")
        return 1

    refs, missing = built_catalog_refs()
    if missing:
        print(RED + "FAIL" + OFF + "  bundle(s) with no catalog_ref in meta: " + ", ".join(missing))
        return 1

    cur_json = read(CATALOG_JSON)
    try:
        total_types = len(json.loads(cur_json)["types"])
    except (ValueError, KeyError) as e:
        print(RED + "FAIL" + OFF + "  catalog-data.json is not valid: " + str(e))
        return 1

    out_of_range = sorted(r for r in refs if not (1 <= r <= total_types))
    if out_of_range:
        print(RED + "FAIL" + OFF + "  catalog_ref out of range for a %d-type catalog: %s"
              % (total_types, out_of_range))
        return 1

    want_json = rebuild_catalog_json_text(cur_json, refs)
    cur_html = read(ATLAS_HTML)
    want_html = rebuild_atlas_html(cur_html, want_json)
    n = len(refs)

    if check:
        drift = []
        if cur_json != want_json:
            drift.append("atlas/catalog-data.json")
        if cur_html != want_html:
            drift.append("atlas/atlas.html")
        if drift:
            print(RED + "FAILED" + OFF + "  atlas is stale in: " + ", ".join(drift))
            print("        run `python tools/gen-atlas.py` to sync the built flags "
                  "(%d bundles built)." % n)
            return 1
        print(GREEN + "OK" + OFF + "  atlas is fresh: %d built bundles, "
              "catalog-data.json and atlas.html agree." % n)
        return 0

    changed = []
    if cur_json != want_json:
        with open(CATALOG_JSON, "w", encoding="utf-8", newline="\n") as f:
            f.write(want_json)
        changed.append("catalog-data.json")
    if cur_html != want_html:
        with open(ATLAS_HTML, "w", encoding="utf-8", newline="\n") as f:
            f.write(want_html)
        changed.append("atlas.html")
    if changed:
        print(GREEN + "OK" + OFF + "  wrote %s: %d built bundles." % (" + ".join(changed), n))
    else:
        print(GREEN + "OK" + OFF + "  atlas already current: %d built bundles." % n)
    return 0


if __name__ == "__main__":
    sys.exit(main())
