#!/usr/bin/env python3
"""gen-atlas.py - generate (or verify) the atlas's `built` flags from the actual bundles.

The Product Artifact Atlas (atlas/atlas.html) shows, per catalog type, whether the library has
BUILT a bundle for it (the "Built" filter). That state lived in two hand-maintained copies - the
`built` boolean in atlas/catalog-data.json AND an identical inline copy embedded in atlas.html's
`<script id="catalog-data" type="application/json">` island - generated by nothing and checked by
nothing. It drifted: for weeks the atlas advertised four built bundles while twelve existed, on the
one surface that is public. Same failure class as the counts that PR #30 corrected, and as the
manifest that ADR 0018 solved for machine consumption: a derived fact kept honest only by memory.

This closes it the same way ADR 0018 closed the manifest. The `built` flag becomes a GENERATED fact,
derived from which catalog types have a bundle under templates/ (matched by each bundle meta's
catalog_ref, the 1-indexed position of its type in catalog-data.json). catalog-data.json is the
single source of truth for the type data; atlas.html's JSON island is regenerated to hold exactly
catalog-data.json's content, so the two can no longer disagree. `--check` regenerates in memory and
fails on drift, the same discipline gen-manifest, the link gate, and the dashes gate already use.

The `state` field is derived the same way and for the same reason, added 2026-08-22 under ADR 0041.
`built` answers "is there a bundle"; `state` answers "and if not, why not", so that 179 unbuilt types stop
reading as undifferentiated gaps. Its four values are `built` (derived from the tree), `queued` and
`out-of-scope` (decisions, so they live in atlas/state-overrides.json with a reason each), and `candidate`
(the default for everything else: eligible, unranked, refused by nobody).

ADR 0041 named the value `candidate` rather than the spec's original `pull-gated`, because that name
asserted a demand gate ADR 0039 had already removed.

Only `built` and `state` are derived here. Every other field in catalog-data.json (categories, stages,
the per-type catalog data) is hand-maintained and preserved untouched.

Usage:
    python tools/gen-atlas.py            # rewrite catalog-data.json + atlas.html built flags in place
    python tools/gen-atlas.py --check    # exit 1 if either file has drifted from the bundles on disk

Exit 0 if written / in sync; 1 if --check finds drift (or the inputs are malformed).
"""

import json
import os
import re
import sys

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.normpath(os.path.join(SCRIPT_DIR, ".."))
TEMPLATES_DIR = os.path.join(ROOT, "templates")
CATALOG_JSON = os.path.join(ROOT, "atlas", "catalog-data.json")
ATLAS_HTML = os.path.join(ROOT, "atlas", "atlas.html")
STATE_OVERRIDES = os.path.join(ROOT, "atlas", "state-overrides.json")

# The JSON island in atlas.html: a self-contained data block the offline page reads. Its content is
# kept byte-identical to catalog-data.json so there is exactly one source of truth for the type data.
ISLAND_RE = re.compile(
    r'(<script id="catalog-data" type="application/json">)(.*?)(</script>)', re.S
)
# The digits after the key; tolerates a trailing inline comment (some metas write
# `catalog_ref: 29   # entry number in the master catalog`).
CATALOG_REF_RE = re.compile(r"^catalog_ref:\s*(\d+)", re.MULTILINE)

GREEN = "\033[32m"
RED = "\033[31m"
OFF = "\033[0m"


def read(path):
    with open(path, encoding="utf-8") as f:
        return f.read()


def built_catalog_refs():
    """The set of catalog numbers that have a built bundle, from each bundle meta's catalog_ref."""
    refs = set()
    missing = []
    for name in sorted(os.listdir(TEMPLATES_DIR)):
        d = os.path.join(TEMPLATES_DIR, name)
        meta = os.path.join(d, name + "_meta.yaml")
        if not os.path.isfile(meta):
            continue  # not a bundle dir (e.g. methodology.md, _working/)
        m = CATALOG_REF_RE.search(read(meta))
        if m:
            refs.add(int(m.group(1)))
        else:
            missing.append(name)
    return refs, missing


def read_state_overrides():
    """The decisions `state` cannot derive from the tree: what is refused, and what is queued.

    Returns (out_of_scope, queued) as id -> reason dicts. Keys beginning with an underscore are
    documentation for whoever opens the file and are ignored here.
    """
    if not os.path.isfile(STATE_OVERRIDES):
        return {}, {}
    data = json.loads(read(STATE_OVERRIDES))
    return data.get("out-of-scope", {}) or {}, data.get("queued", {}) or {}


def rebuild_catalog_json_text(current_text, refs, out_of_scope, queued):
    """Return catalog-data.json's text with `built` and `state` derived, everything else kept.

    A type's catalog number is its 1-indexed position in the types array (the ordering the catalog's
    own numbering uses; verified: catalog_ref N maps to types[N-1]).

    Precedence is deliberate: a bundle on disk wins over any override, so `state` cannot claim a type
    is refused or queued while its bundle exists. That contradiction is reported by validate_overrides
    rather than silently resolved.
    """
    data = json.loads(current_text)
    types = data["types"]
    for i, t in enumerate(types):
        built = (i + 1) in refs
        t["built"] = built
        tid = t.get("id")
        if built:
            t["state"] = "built"
            t["state_note"] = ""
        elif tid in out_of_scope:
            t["state"] = "out-of-scope"
            t["state_note"] = out_of_scope[tid]
        elif tid in queued:
            t["state"] = "queued"
            t["state_note"] = queued[tid]
        else:
            t["state"] = "candidate"
            t["state_note"] = ""
    # Exactly the serialization the committed file already uses (indent 2, unicode, no trailing NL).
    return json.dumps(data, indent=2, ensure_ascii=False)


def validate_overrides(current_text, refs, out_of_scope, queued):
    """Fail on an override that names a type the catalog does not have, or one that is already built.

    Both are the same class of defect the `built` flag had before it was generated: a hand-maintained
    claim with nothing checking it against the tree.
    """
    data = json.loads(current_text)
    ids = {t.get("id"): i + 1 for i, t in enumerate(data["types"])}
    problems = []
    for label, table in (("out-of-scope", out_of_scope), ("queued", queued)):
        for tid, reason in table.items():
            if tid not in ids:
                problems.append("%s: '%s' is not a catalog type id" % (label, tid))
                continue
            if ids[tid] in refs:
                problems.append(
                    "%s: '%s' has a bundle on disk, so its state is 'built' and the override is a "
                    "contradiction" % (label, tid))
            if not str(reason).strip():
                problems.append("%s: '%s' has no reason, and every entry must carry one" % (label, tid))
    return problems


def rebuild_atlas_html(current_html, catalog_json_text):
    """Return atlas.html with its JSON island replaced by catalog_json_text."""
    if not ISLAND_RE.search(current_html):
        raise SystemExit(RED + "FAIL" + OFF + "  atlas.html has no <script id=\"catalog-data\"> island")
    return ISLAND_RE.sub(
        lambda m: m.group(1) + catalog_json_text + m.group(3), current_html, count=1
    )


def main():
    check = "--check" in sys.argv[1:]

    if not os.path.isfile(CATALOG_JSON) or not os.path.isfile(ATLAS_HTML):
        print(RED + "FAIL" + OFF + "  atlas/catalog-data.json or atlas/atlas.html is missing")
        return 1

    refs, missing = built_catalog_refs()
    if missing:
        print(RED + "FAIL" + OFF + "  bundle(s) with no catalog_ref in meta: " + ", ".join(missing))
        return 1

    cur_json = read(CATALOG_JSON)
    try:
        total_types = len(json.loads(cur_json)["types"])
    except (ValueError, KeyError) as e:
        print(RED + "FAIL" + OFF + "  catalog-data.json is not valid: " + str(e))
        return 1

    out_of_range = sorted(r for r in refs if not (1 <= r <= total_types))
    if out_of_range:
        print(RED + "FAIL" + OFF + "  catalog_ref out of range for a %d-type catalog: %s"
              % (total_types, out_of_range))
        return 1

    out_of_scope, queued = read_state_overrides()
    problems = validate_overrides(cur_json, refs, out_of_scope, queued)
    if problems:
        print(RED + "FAIL" + OFF + "  atlas/state-overrides.json disagrees with the catalog:")
        for line in problems:
            print("        " + line)
        return 1

    want_json = rebuild_catalog_json_text(cur_json, refs, out_of_scope, queued)
    cur_html = read(ATLAS_HTML)
    want_html = rebuild_atlas_html(cur_html, want_json)
    n = len(refs)

    if check:
        drift = []
        if cur_json != want_json:
            drift.append("atlas/catalog-data.json")
        if cur_html != want_html:
            drift.append("atlas/atlas.html")
        if drift:
            print(RED + "FAILED" + OFF + "  atlas is stale in: " + ", ".join(drift))
            print("        run `python tools/gen-atlas.py` to sync the built flags "
                  "(%d bundles built)." % n)
            return 1
        print(GREEN + "OK" + OFF + "  atlas is fresh: %d built bundles, "
              "catalog-data.json and atlas.html agree." % n)
        return 0

    changed = []
    if cur_json != want_json:
        with open(CATALOG_JSON, "w", encoding="utf-8", newline="\n") as f:
            f.write(want_json)
        changed.append("catalog-data.json")
    if cur_html != want_html:
        with open(ATLAS_HTML, "w", encoding="utf-8", newline="\n") as f:
            f.write(want_html)
        changed.append("atlas.html")
    if changed:
        print(GREEN + "OK" + OFF + "  wrote %s: %d built bundles." % (" + ".join(changed), n))
    else:
        print(GREEN + "OK" + OFF + "  atlas already current: %d built bundles." % n)
    return 0


if __name__ == "__main__":
    sys.exit(main())
